## Introduction

Customer segmentation is the process of dividing customers into groups based on purchasing behaviour. This allows businesses to target marketing strategies effectively and improve customer retention.

## Business Problem

Companies often have thousands of customers but lack a structured method to understand purchasing behaviour. Without segmentation, marketing campaigns are inefficient and resources are wasted on customers who may not respond.

Customer segmentation helps businesses group customers based on purchasing patterns so that companies can deliver targeted marketing strategies.

## Project Objective

This project aims to transition the business from a mass-marketing approach to a targeted strategy. By applying machine learning to transactional data, we will group customers into distinct segments based on their purchasing behavior, allowing for personalized marketing, optimized retention strategies, and ultimately, increased revenue.

## Dataset Description

Dataset Selection & Justification
To solve this problem, we selected the Online Retail Dataset (sourced from the UCI Machine Learning Repository). It contains 541,909 real-world transactional records from a UK-based e-commerce store between December 2010 and December 2011.

Why this dataset is highly suitable:

Rich Transactional Depth: It includes InvoiceDate, Quantity, UnitPrice, and CustomerID, which are the exact features required to calculate RFM (Recency, Frequency, Monetary) metrics the gold standard for behavioral segmentation.

Real-World Complexity: Unlike simplified "toy" datasets, this data contains real business challenges (e.g., returns/cancellations, missing values, wholesale vs. retail customers) that require robust data engineering, demonstrating our technical capability.

Limitations to address:
Approximately 25% of the records lack a CustomerID. Since our goal is customer segmentation, these anonymous transactions cannot be tracked over time and will be systematically removed during the data-cleaning phase to maintain the integrity of our model.

This project uses the Online Retail Dataset, which contains transactions occurring between December 2010 and December 2011 for a UK-based online retailer.

The dataset includes:

Invoice number

StockCode

Product description

Quantity purchased

Transaction date

Customer ID

Country

Unit price

These variables allow analysis of customer purchasing behaviour.

## Why This Dataset Was Selected

The dataset was selected because it contains real transactional data, enabling the analysis of purchasing frequency, spending patterns, and customer value. This makes it suitable for performing customer segmentation using clustering techniques.

In [3]:
import pandas as pd

df = pd.read_excel("Online_Retail.xlsx")

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [5]:
df.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  541909.000000                      541909  541909.000000  406829.000000
mean        9.552250  2011-07-04 13:34:57.156386       4.611114   15287.690570
min    -80995.000000         2010-12-01 08:26:00  -11062.060000   12346.000000
25%         1.000000         2011-03-28 11:34:00       1.250000   13953.000000
50%         3.000000         2011-07-19 17:17:00       2.080000   15152.000000
75%        10.000000         2011-10-19 11:27:00       4.130000   16791.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       218.081158                         NaN      96.759853    1713.600303

# Remove missing Customer IDs

In [13]:
df = df.dropna(subset=['CustomerID'])

# Remove negative quantities

In [11]:
df = df[df['Quantity'] > 0]

# Remove invalid prices

In [12]:
df = df[df['UnitPrice'] > 0]